#!/bin/sh
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=8192M  # that much memory for simulation and reconstruction jobs only
#SBATCH --time=14-00:00:0
#SBATCH -p nica


source /cvmfs/nica.jinr.ru/sw/os/login.sh
module add mpddev
export MPDROOT=/lhep/users/jcmarqzra/mpd
source /lhep/users/jcmarqzra/mpd/config/env.sh 


root -l -b -q "RunAnalyses.C"
